2020-08-27 10:19:24.1460||DEBUG|uccApiCore2.Program|init main |url: |action: 
2020-08-27 10:27:47.4331||ERROR|Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware|An unhandled exception has occurred while executing the request System.Data.SqlClient.SqlException (0x80131904): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (258): The wait operation timed out
   at uccApiCore2.Repository.LookupRepository.GetActiveColor() in C:\Project\Mohit\EcommApiCore\uccApiCore2.Repository\LookupRepository.cs:line 24
   at uccApiCore2.Controllers.LookupController.GetActiveColor() in C:\Project\Mohit\EcommApiCore\uccApiCore2\Controllers\LookupController.cs:line 29
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
ClientConnectionId:002be26e-14c0-4ae4-affe-10cb981c9b10
Error Number:-2,State:0,Class:11|url: http://localhost/api/Lookup/GetActiveColor/|action: GetActiveColor
2020-08-27 12:53:47.9184||ERROR|uccApiCore2.Controllers.BrandController|Something went wrong inside BrandController GetAllBrand action: A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 0 - The semaphore timeout period has expired.) |url: http://localhost/api/Brand/GetAllBrand/|action: GetAllBrand
2020-08-27 16:18:15.4605||DEBUG|uccApiCore2.Program|init main |url: |action: 
2020-08-27 16:18:41.6531||DEBUG|uccApiCore2.Program|init main |url: |action: 
2020-08-27 16:50:43.1102||DEBUG|uccApiCore2.Program|init main |url: |action: 
2020-08-27 16:56:04.2389||DEBUG|uccApiCore2.Program|init main |url: |action: 
2020-08-27 16:58:57.0903||DEBUG|uccApiCore2.Program|init main |url: |action: 
2020-08-27 16:59:32.6996||ERROR|uccApiCore2.Controllers.OrderController|Something went wrong inside OrderController SaveOrder action: Index was outside the bounds of the array. |url: http://localhost/api/Order/SaveOrder|action: SaveOrder
2020-08-27 16:59:34.5371||ERROR|uccApiCore2.Controllers.OrderController|Something went wrong inside OrderController GetOrderByOrderId action: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index |url: http://localhost/api/Order/GetOrderByOrderId|action: GetOrderByOrderId
2020-08-27 17:01:02.3894||ERROR|uccApiCore2.Controllers.OrderController|Something went wrong inside OrderController SaveOrder action: Index was outside the bounds of the array. |url: http://localhost/api/Order/SaveOrder|action: SaveOrder
2020-08-27 17:01:04.3998||ERROR|uccApiCore2.Controllers.OrderController|Something went wrong inside OrderController GetOrderByOrderId action: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index |url: http://localhost/api/Order/GetOrderByOrderId|action: GetOrderByOrderId
2020-08-27 18:27:47.4730||DEBUG|uccApiCore2.Program|init main |url: |action: 
2020-08-27 18:28:10.3402||ERROR|uccApiCore2.Controllers.OrderController|Something went wrong inside OrderController GetOrderByOrderId action: One or more errors occurred. (A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)) |url: http://localhost/api/Order/GetOrderByOrderId|action: GetOrderByOrderId
2020-08-27 18:28:10.3402||ERROR|uccApiCore2.Controllers.CartController|Something went wrong inside CartController GetCartById action: One or more errors occurred. (A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)) |url: http://localhost/api/Cart/GetCartById|action: GetCartById
2020-08-27 18:28:10.3402||ERROR|uccApiCore2.Controllers.UsersController|Something went wrong inside UsersController checkMobileAllReadyRegisteredOrNot action: One or more errors occurred. (A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)) |url: http://localhost/api/Users/CheckMobileAllReadyRegisteredOrNot|action: CheckMobileAllReadyRegisteredOrNot
2020-08-27 18:28:10.3448||ERROR|uccApiCore2.Controllers.ProductController|Something went wrong inside ProductController GetProductBySubcatecode action: One or more errors occurred. (A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)) |url: http://localhost/api/Product/GetProductBySubcatecode|action: GetProductBySubcatecode
2020-08-27 18:28:51.6528||DEBUG|uccApiCore2.Program|init main |url: |action: 
2020-08-27 18:42:21.2470||DEBUG|uccApiCore2.Program|init main |url: |action: 
2020-08-27 18:53:39.1493||DEBUG|uccApiCore2.Program|init main |url: |action: 
2020-08-27 18:54:58.0240||DEBUG|uccApiCore2.Program|init main |url: |action: 
2020-08-27 18:55:56.5650||ERROR|uccApiCore2.Controllers.UsersController|Something went wrong inside UsersController UserRegistration action: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index |url: http://localhost/api/Users/UserRegistration|action: UserRegistration
2020-08-27 18:56:01.7877||ERROR|Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware|An unhandled exception has occurred while executing the request System.NullReferenceException: Object reference not set to an instance of an object.
   at uccApiCore2.Controllers.UsersController.UserRegistration(Users obj) in C:\Project\Mohit\EcommApiCore\uccApiCore2\Controllers\UsersController.cs:line 148
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)|url: http://localhost/api/Users/UserRegistration|action: UserRegistration
2020-08-27 18:56:21.0824||ERROR|uccApiCore2.Controllers.UsersController|Something went wrong inside UsersController UserRegistration action: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index |url: http://localhost/api/Users/UserRegistration|action: UserRegistration
2020-08-27 18:56:22.0710||ERROR|Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware|An unhandled exception has occurred while executing the request System.NullReferenceException: Object reference not set to an instance of an object.
   at uccApiCore2.Controllers.UsersController.UserRegistration(Users obj) in C:\Project\Mohit\EcommApiCore\uccApiCore2\Controllers\UsersController.cs:line 148
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)|url: http://localhost/api/Users/UserRegistration|action: UserRegistration
2020-08-27 18:56:31.2524|22|WARN|Microsoft.AspNetCore.Server.Kestrel|Heartbeat took longer than "00:00:01" at "08/27/2020 13:26:30 +00:00". |url: |action: 
2020-08-27 18:56:38.3985||ERROR|uccApiCore2.Controllers.UsersController|Something went wrong inside UsersController UserRegistration action: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index |url: http://localhost/api/Users/UserRegistration|action: UserRegistration
2020-08-27 18:56:39.4816||ERROR|Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware|An unhandled exception has occurred while executing the request System.NullReferenceException: Object reference not set to an instance of an object.
   at uccApiCore2.Controllers.UsersController.UserRegistration(Users obj) in C:\Project\Mohit\EcommApiCore\uccApiCore2\Controllers\UsersController.cs:line 148
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)|url: http://localhost/api/Users/UserRegistration|action: UserRegistration
2020-08-27 18:56:58.3278||ERROR|uccApiCore2.Controllers.UsersController|Something went wrong inside UsersController UserRegistration action: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index |url: http://localhost/api/Users/UserRegistration|action: UserRegistration
2020-08-27 18:56:59.8580||ERROR|Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware|An unhandled exception has occurred while executing the request System.NullReferenceException: Object reference not set to an instance of an object.
   at uccApiCore2.Controllers.UsersController.UserRegistration(Users obj) in C:\Project\Mohit\EcommApiCore\uccApiCore2\Controllers\UsersController.cs:line 148
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)|url: http://localhost/api/Users/UserRegistration|action: UserRegistration
2020-08-27 18:57:35.0856||ERROR|uccApiCore2.Controllers.UsersController|Something went wrong inside UsersController UserRegistration action: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index |url: http://localhost/api/Users/UserRegistration|action: UserRegistration
2020-08-27 18:58:27.5951||DEBUG|uccApiCore2.Program|init main |url: |action: 
2020-08-27 19:03:04.6870||DEBUG|uccApiCore2.Program|init main |url: |action: 
2020-08-27 19:03:26.0871||ERROR|uccApiCore2.Controllers.UsersController|Something went wrong inside UsersController UserRegistration action: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified) |url: http://localhost/api/Users/UserRegistration|action: UserRegistration
2020-08-27 21:37:13.4632||ERROR|uccApiCore2.Controllers.UsersController|Something went wrong inside UsersController ValidLogin action: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified) |url: http://localhost/api/Users/ValidLogin/|action: ValidLogin
